### ISSUE TITLE
Feature: User can sign in to their spotify account to authorize Songify to access and edit the data

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in to their spotify account to authorize Songify to access and edit the data

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user will be redirected to the Spotify Authentication page to allow Songify to access and edit the data. Then the user will be able to use the song recommendation feature.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a .env file to store Spotify clientId and clientSecret
- [x] Install all necessary packages, passport-spotify, passport, express-session,etc.
- [x] Update `server/index.js` to ...
- [x] import all installed packages
- [x] Set up all require middleware
- [x] Set up port for the server
- [x] Write all routing methods:
    - [x] get:
        - [x] spotify authenticatication redirect page

        - [x] callback method
        - [x] root/ homepage method 
        - [x] handle callback redirect method
- [x] listen for the set port
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the homepage (the first thing the user sees)
- [x] Create a header component
- [x] Add button functionality
- [x] Create a component to render thauthenticationon page
- [x] Create a component to render callback page after the user is authenticated
- [x] Create a component to render callback page after the user denies Songify access
- [x] connect the callback page to the backend callback function

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
