### ISSUE TITLE
Feature #7: User can view liked songs

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-17 at 10 06 48 AM](https://user-images.githubusercontent.com/52221756/133827223-1500d512-96a1-48df-aaa1-a727f2c77473.png)
![Screen Shot 2021-09-17 at 10 07 00 AM](https://user-images.githubusercontent.com/52221756/133827227-8717bc77-615e-4366-adb0-ce75bef0ddc6.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create a hash route from the endOfRecommendation button to the loved songs page
- [x] Create a component to display the array of loved songs 
- [x] style the component
- [x] create 2 buttons for each song in the array
    - [x] one to remove the song from the array
    - [x] one to add the song to their songify playlist in their spotify account:
- [x]  create a 'view songify playlist' button 

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
