### ISSUE TITLE
Feature #8:User can add liked song to Songify playlist

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ..
- [x] create a http get request to create a playlist
- [x] create a get request to add a track to the playlist 

### ⚡ Client

- [x] create an anchor tag with the text "View Songify playlist"
- [x] style anchor tag
- [x] create a button that adds the liked songs to the Songify playlist
- [x] call the fetch request to add the tracks to the playlist when the button is pressed
- [x] create the playlist as soon as the user is redirected to the liked songs page

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [ ]
