### ISSUE TITLE
Feature #9: User can view Songify playlist

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view Songify playlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
after adding all the songs to thier playlist on spotify, users can view what songs were actually added to the playlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-20 at 11 14 37 AM](https://user-images.githubusercontent.com/52221756/134053452-f186cc0b-7828-43d6-9e08-048a4ee614f6.png)

![Screen Shot 2021-09-20 at 11 14 23 AM](https://user-images.githubusercontent.com/52221756/134053461-643e8e3c-a26a-4c7a-a54a-ce600424bf24.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create Playlist class to display the playlist songs 
- [x] style the class 
- [x] pass in the songs added to the playlist and their info
- [x] use song song info to display songs (name, artist, cover, spotify link)

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
