### ISSUE TITLE
Feature #2: User can enter a song name, artist and genre of their favorite song to generate recommendations

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter a song name, artist and genre of their favorite song to generate recommendations

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
After clicking the "Get recommendtaions" buttons the user 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-11 at 8 23 52 PM](https://user-images.githubusercontent.com/52221756/132970936-18bb34f1-88a4-4d6e-a36f-92da53890f03.png)
![Screen Shot 2021-09-11 at 8 23 37 PM](https://user-images.githubusercontent.com/52221756/132970937-9d8fc241-88d9-4253-9a11-00cdcd02f4f8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a react SongForm class and jsx file 
- [x] create a data model in the constructor to store songInfo
- [x] Create a form-page component
    - [x] Create a form element with 3 elements (2 input elements, 1 drop down sleect menu for genres)
    - [x] stye the form using bootstrap's conatiner element 
    - [x] bond handleChange and handleSumbit methods
    - [x] create handleChange method:
        - [x] update songInfo data model 
        - [x]  update state to include artist, songName, genre
        - [x]  => this.setState({ value: event.target.value });
    - [x] create a handleSubmit method:
            - [ ] prevent the page from resetting using the preventDefault()

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
