### ISSUE TITLE
Feature #3: User can view recommended song information (album, artist, year, etc)

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view recommended song information (album, artist, year, etc)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-13 at 3 06 10 PM](https://user-images.githubusercontent.com/52221756/133162749-de4a76f9-cd2c-4d6e-a154-394a1237f009.png)
![Screen Shot 2021-09-13 at 3 05 54 PM](https://user-images.githubusercontent.com/52221756/133162755-226b62c8-5e6e-4b2d-9aab-2d4363ff8c04.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature

### ☁️ Server

- [x] Update `server/index.js` to ...
    - [x] create a get method search for songId based on artist and song name
        - [x] store song-data in a cookie to be passed to client-side
    - [x] create a get method to get the song reccommendation based on the genere, song name, and artist
        - [x] format output data into an array 
            - [x] filter out unnecessary data from data output 
        - [x] store recommendation array in a cookie to pass on to client-server
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to store song-info dummy data
    - [x] style component using bootstrap grid system
    - [x] style 2 buttons (yes and no)
- [x] Update component to display based on current-sonrecommendationon info passed as a prop.
- [x] update sosng-form button to redirect page to song-info page using hash routing.
    - [x] update app.jsx with current screen.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
