### ISSUE TITLE
Feature #4: User can skip the recommended song

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/Songify#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can skip the recommended song

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After submitting the form the user will see a single recommended song at a time, the user can click on the skip song button, to display a different song (the next song in the recommendation array).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-16 at 10 12 28 AM](https://user-images.githubusercontent.com/52221756/133655977-98f50d21-de9a-4cb4-b8bd-d102928f2610.png)
![Screen Shot 2021-09-16 at 10 12 19 AM](https://user-images.githubusercontent.com/52221756/133655979-d9313f42-ba5a-4cbd-ab32-80147bdfee74.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] update the callback method in the Recommendation class to increment the currentIndex to move on to the next song object in the array 
- [x] call the parent (recommendations) callback method, passed in as a prop, in the child component (SongInfo) when the skip button is pressed.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
